<?php
$documents = [
  'Evaluacion-y-acreditacion.-APACET' => [
    [
      'title' => 'Nuevo Consejo Consultivo',
      'description' => 'Exposición del Dr. Jorge Ares Pons en el acto de asunción de las nuevas autoridades del Consejo Consultivo de Enseñanza Terciaria Privada, realizado el 27 de junio de 2005 en la sede del Ministerio de Educación y Cultura',
      'date' => 'Junio de 2005',
      'fileName' => 'Nuevo-Consejo-Consultivo.pdf',
    ],
    [
      'title' => 'Correspondencia a los legisladores sobre APACET',
      'description' => 'Comentarios sobre el proyecto de "Ley de Creación de una Agencia de Acreditación (APACET) para la Promoción y el Aseguramiento de la Calidad de la Educación Terciaria"',
      'date' => 'Marzo de 2010',
      'fileName' => 'Correo-a-legisladores-sobre-APACET.-Marzo-2010.pdf',
    ],
    [
      'title' => 'Correo a legisladores sobre APACET',
      'description' => '',
      'date' => 'Abril de 2012',
      'fileName' => 'Correo-a-legisladores-sobre-APACET.-Abril-2012.pdf',
    ],
    [
      'title' => 'Consejo Consultivo de Enseñanza Terciaria Privada (CCETP) período 2005-2008 cese',
      'description' => '',
      'date' => 'Junio de 2008',
      'fileName' => 'Consejo-Consultivo-cese.-Junio-08.pdf',
    ],
    [
      'title' => 'Consejo Consultivo de Enseñanza Terciaria Privada (CCETP) Toma de posesión de nuevas autoridades',
      'description' => '',
      'date' => 'Noviembre de 2008',
      'fileName' => 'CCETP-Toma-de-posesion-de-nuevas-autoridades.-Nov.-08.pdf',
    ],
    [
      'title' => 'Association of Independent Colleges and Schools (AICS) (Ciclo 1989)',
      'description' => '',
      'date' => 'Julio de 2007',
      'fileName' => 'Association-of-Independent-Colleges-and-Schools-(AICS)-Requisitos.pdf',
    ],
    [
      'title' => 'Comentarios sobre la ley de creación de una agencia de acreditación (APACET) para la promoción y el aseguramiento de la calidad de la educación terciaria',
      'description' => 'Proyecto a elevar por el Ministerio de Educación y Cultura (MEC) al Poder Ejecutivo en agosto de 2009, elevado a la Asamblea General el 18 de setiembre de 2009',
      'date' => '2009',
      'fileName' => 'AGENCIA-COMENTARIOS-No1-APACET-VERSION-FINAL.pdf',
    ],
    [
      'title' => 'Independencia y autonomia de la proyectada "Agencia de Promoción y Aseguramiento de la Calidad de la Educación Terciaria" (APACET)',
      'description' => '',
      'date' => 'Junio de 2011',
      'fileName' => 'AGENCIA-APACET-No-3-Independencia-y-autonomia-de-funcionamiento.pdf',
    ],
    [
      'title' => 'Sobre la ceración de la "Agencia de Promoción y Aseguramiento de la Calidad de la Educación Terciaria" (APACET)',
      'description' => '',
      'date' => 'octubre de 2009',
      'fileName' => 'AGENCIA-2o-documento-sobre-APACET.pdf',
    ],
  ],
  "LibrosOtros" => [
    [
      'title' => 'Índice del libro "Universidad: ¿Anarquía organizada?"',
      'description' => '',
      'fileName' => 'Universidad:-Anarquia-organizada.pdf',
    ],
    [
      'title' => 'Miserias de las ciudades de los hombres y otras servidumbres',
      'description' => '',
      'fileName' => 'Miserias-de-las-ciudades-de-los-hombres-y-otras-servidumbres.pdf',
    ],
    [
      'title' => 'CURRICULUM VITAE',
      'description' => '',
      'fileName' => 'CURRICULUM-VITAE.pdf',
    ],
    [
      'title' => 'CURRICULUM COMPLEMENTO 1',
      'description' => 'Renuncia al CDC como delegado del Orden Docente',
      'date' => 'Mayo de 1989',
      'fileName' => 'CURRICULUM-COMPLEMENTO-1.pdf',
    ],
    [
      'title' => 'CURRICULUM COMPLEMENTO 2',
      'description' => 'Renuncia al CDC como delegado del Orden Egresados',
      'date' => 'Noviembre de 1991',
      'fileName' => 'CURRICULUM-COMPLEMENTO-2.pdf',
    ],
  ],
  'Universidad-y-PEDECIBA' => [
    [
      'title' => 'La regulación de la Enseñanza Terciaria en el Uruguay. Historia y situación actual',
      'description' => 'Seminario: La Evaluación y Acreditación en Instituciones de Educación Superior. Autoevaluación y Evaluación Externa, desafíos e instrumentos',
      'date' => 'Abril de 2009',
      'fileName' => 'UNESCO-seminario.pdf',
    ],
    [
      'title' => 'La Universidad de la República y la formación docente',
      'description' => '"Jornadas Universitarias de Formación Didáctica" 6 y 7 de diciembre de 2006',
      'date' => 'Diciembre de 2006',
      'fileName' => 'UDELAR-y-Formacion-Docente.pdf',
    ],
    [
      'title' => 'Trascendencia del PEDECIBA',
      'description' => 'Gaceta universitaria / Año 3 / Nº1 / 1989',
      'date' => '1989',
      'fileName' => 'Trascendencia-del-PEDECIBA.pdf',
    ],
    [
      'title' => 'Comentarios previos sobre la carrera: "Especialización en Psicología Sistémica y Familias", presentada por la UCU',
      'description' => '',
      'date' => 'Noviembre de 2005',
      'fileName' => 'Psicologia-Sistemica.-Especializacion.pdf',
    ],
    [
      'title' => 'Calificación de planteles docentes para el dictado de posgrados universitarios stricto sensu',
      'description' => '',
      'date' => 'Octubre de 2005',
      'fileName' => 'Posgrados-y-Savello.-Maestrias-profesionales.pdf',
    ],
    [
      'title' => 'Pautas para la organización de un Sistema de Enseñanza Terciaria en el Uruguay',
      'description' => '',
      'date' => 'julio de 1998',
      'fileName' => 'Pautas-para-la-organizacion-de-un-Sistema-de-Ensenanza-Terciaria-en-el-Uruguay.pdf',
    ],
    [
      'title' => 'Ordenamiento de la Enseñanza Terciaria en el Uruguay',
      'description' => '',
      'date' => 'Abril de 1997',
      'fileName' => 'Ordenamiento-de-la-Ensenanza-Terciaria-en-el-Uruguay.pdf',
    ],
    [
      'title' => 'Libertad de enseñanza y restricciones legales',
      'description' => '',
      'date' => 'Noviembre de 2001',
      'fileName' => 'LIbertad-y-Restricciones.pdf',
    ],
    [
      'title' => 'Grado y Posgrado. Reconocimento de áreas disciplinarias no afines (inc. a) del Art. 4º del D. 308/95) en base solamente a posgrados',
      'description' => '',
      'date' => 'Julio de 1996',
      'fileName' => 'Grado-y-Posgrado.pdf',
    ],
    [
      'title' => 'Fundamentación de los contenidos del Anteproyecto de ley de educación terciaria privada',
      'description' => '',
      'date' => '1998',
      'fileName' => 'Fundamentacion-del-Anteproyecto-de-UDELAR-de-1998.pdf',
    ],
    [
      'title' => 'Formación docente',
      'description' => 'Dos vertientes: "formación docente" y "carrera docente"',
      'fileName' => 'Formacion-docente.pdf',
    ],
    [
      'title' => 'El Programa para el Desarrollo de las Ciencias Básicas (PEDECIBA)',
      'description' => '',
      'date' => 'Setiembre de 2004',
      'fileName' => 'El-Programa-para-el-Desarrollo-de-las-Ciencias-Basicas-(PEDECIBA).pdf',
    ],
    [
      'title' => 'Dos documentos oficiales del CDC de la UdelaR',
      'description' => 'Concepto de Universidad, Concepto de Educación Superior en la tradición nacional',
      'date' => '1990',
      'fileName' => 'Dos-documentos-oficiales-del-CDC.pdf',
    ],
    [
      'title' => 'Discusión a propósito de un Sistema Nacional de Educación',
      'description' => '',
      'date' => 'Setiembre de 2005',
      'fileName' => 'Discusion-a-proposito-de-un-Sistema-Nacional-de-Educacion.pdf',
    ],
      [
      'title' => 'Correspondencia al rector Arocena: trayectoria y la situación de la Comisión Universitaria de Enseñanza Terciaria Privada (CUETP)',
      'description' => '',
      'date' => 'Setiembre de 2007',
      'fileName' => 'CUETP.pdf',
    ],
    [
      'title' => 'Citas para Carrera Docente',
      'description' => '',
      'date' => 'Noviembre de 2006',
      'fileName' => 'Citas-para-Carrera-Docente.pdf',
    ],
    [
      'title' => 'Las autonomías universitarias',
      'description' => '',
      'date' => 'Diciembre de 2008',
      'fileName' => 'AUTONOMIAS-UNIVERSITARIAS.pdf',
    ],
    [
      'title' => 'Anteproyecto de Ley de Educación Terciaria Privada',
      'description' => '',
      'date' => 'Febrero de 1998',
      'fileName' => 'Anteproyecto-de-Ley-de-Ensenanza-Terciaria-Privada.pdf',
    ],
    [
      'title' => 'Luces y Sombras. Leyes y cambios. Papel de la docencia universitaria',
      'description' => '',
      'date' => 'Julio de 2009',
      'fileName' => 'AGC-Paneles-sobre-Universidad.-Luces-y-Sombras.pdf',
    ],
  ],
  'Universidad-y-sociedad' => [
    [
      'title' => 'Hitos universitarios',
      'description' => '',
      'fileName' => 'Hitos-universitarios.pdf',
    ],
    [
      'title' => 'Universidades públicas y privadas. ¿Convergencia, convivencia o conflicto?',
      'description' => 'IV Jornadas Nacionales del 2000. Grupo de Trabajo Hacer la Historia: "UNIVERSIDAD Y SOCIEDAD" Universidad Nacional de Rosario, Facultad de Humanidades y Artes 13 y 14 octubre 2000',
      'date' => 'Versión corregida 2005',
      'fileName' => 'Universidades-publicas-y-privadas.-Convergencia-convivencia-o-conflicto.pdf',
    ],
    [
      'title' => 'Terciario y Universitario. Licenciados y Técnicos',
      'description' => '',
      'fileName' => 'Terciario-y-Universitario.-Licenciados-y-Tecnicos.pdf',
    ],
    [
      'title' => 'Técnica y Tecnología. Técnicos y Tecnólogos',
      'description' => '',
      'date' => 'Mayo de 2003',
      'fileName' => 'Tecnica-y-Tecnologia.-Tecnicos-y-Tecnologos.pdf',
    ],
    [
      'title' => 'Presente y futuro de la Universidad Latinoamericana',
      'description' => 'Revista "Educación Superior y Sociedad", vol. 7, Nº 1: 109-126, Caracas, 1996',
      'date' => '1996',
      'fileName' => 'Presente-y-futuro-de-la-Universidad-Latinoamericana.pdf',
    ],
    [
      'title' => 'Políticas de Estado en materia de Educación',
      'description' => 'IV ENCUENTRO "EDUCACION PARA LA INTEGRACION" SIMPOSIO: ESTADO Y UNIVERSIDAD EN LA INTEGRACION REGIONAL AUGM. UNIVERSIDAD NACIONAL DE ENTRE RIOS. 22-23-24 MAYO 1996 CONCORDIA R.A.',
      'date' => 'Mayo de 1996',
      'fileName' => 'Politicas-de-Estado-en-materia-de-Educacion.pdf',
    ],
    [
      'title' => 'Neoliberalismo y Universidad: conservadores y "renovadores"',
      'description' => 'Cuatro decanos',
      'date' => 'Octubre de 1997',
      'fileName' => 'Cuatro-decanos.pdf',
    ],
    [
      'title' => 'Niveles de titulación',
      'description' => 'EXPEDICION DE TITULOS DE CARRERAS DE INSTITUCIONES UNIVERSITARIAS PRIVADAS',
      'date' => 'Octubre de 2008',
      'fileName' => 'Niveles-de-titulacion.pdf',
    ],
    [
      'title' => 'Reportaje a Jorge Ares Pons',
      'description' => '"Neoliberalismo y universidad" en revista Siete sobre Siete',
      'date' => 'Mayo de 2004',
      'fileName' => 'Jorge-Ares-Pons-Reportaje.pdf',
    ],
    [
      'title' => 'Informe preliminar (Comisión Sectorial de Enseñanza): Carreras técnicas y tecnológicas',
      'description' => 'Comisión Sectorial de Enseñanza',
      'date' => 'Junio de 2005',
      'fileName' => 'Informe-preliminar-(Comision-Sectorial-de-Ensenanza):-Carreras-tecnicas-y-tecnologicas.pdf',
    ],
    [
      'title' => 'Ética y Universidad',
      'description' => 'Extractos',
      'fileName' => 'Etica-y-Universidad-(extractos).pdf',
    ],
    [
      'title' => 'Educación superior: internacionalización e integración regional. Papel de las nuevas tecnologías de la información y comunicación (TIC)',
      'description' => 'IV Cumbre Iberoamericana de Rectores',
      'date' => 'Mayo de 2006',
      'fileName' => 'Cumbre-iberoamericana-de-julio-de-2006.pdf',
    ],
    [
      'title' => 'Cuatro documentos oficiales del CDC de la UDELAR',
      'description' => 'Concepto de Universidad, Concepto de Educación Superior en la tradición nacional, Expedición de títulos, Instituciones provadas de educación superior',
      'date' => '1990',
      'fileName' => 'Cuatro-documentos-oficiales-del-CDC-de-la-UDELAR.pdf',
    ],
    [
      'title' => 'Córdoba 2000',
      'description' => 'Conmemoración de los 80 años del Movimiento Reformista de Córdoba',
      'date' => '1998',
      'fileName' => 'Cordoba-2000.pdf',
    ],
    [
      'title' => 'Condición universitaria',
      'description' => 'IV COLOQUIO SOBRE PENSAMIENTO Y ACTUALIDAD TEORIA DE LA UNIVERSIDAD-Fac.de Humanidades y Ciencias de la Educación, Montevideo, 6-8 de noviembre 2007',
      'date' => 'Octubre de 2007',
      'fileName' => 'Condicion-universitaria.pdf',
    ],
    [
      'title' => 'Concepto de Universidad y Educación Superior. Cronología',
      'description' => '',
      'date' => 'Junio de 1995',
      'fileName' => 'Concepto-de-Universidad-y-Educacion-Superior.-Cronologia-CONAPRO-etc.pdf',
    ],
    [
      'title' => 'Comentarios a propósito de una propuesta del Rector referida a "áreas" y "unidades disciplinarias"',
      'description' => '',
      'date' => 'Setiembre de 1999',
      'fileName' => 'Comentarios-a-proposito-de-una-propuesta-del-Rector-referida-a-"areas"-y-"unidades-disciplinarias".pdf',
    ],
    [
      'title' => 'Concepto de certificados, títulos, diplomas',
      'description' => '',
      'date' => 'Mayo de 2003',
      'fileName' => 'Certificados-titulos-diplomas.pdf',
    ],
    [
      'title' => 'Breve análisis y comentarios sobre los niveles superiores de la CINE 1997',
      'description' => '',
      'date' => 'Octubre de 2000',
      'fileName' => 'Breve-analisis-y-comentarios-sobre-los-niveles-superiores-de-la-CINE-1997.pdf',
    ],
    [
      'title' => 'Alma Bolón: La uniforme celebración de la diversidad',
      'description' => '',
      'date' => 'Noviembre de 2011',
      'fileName' => 'BOLON-ALMA-operti-rama-DIVERSIDAD-EDUCATIVA-DIC-2011.pdf',
    ],
    [
      'title' => 'La Internacionalización de la educación superior',
      'description' => 'Publicado en Bitácora',
      'date' => 'Noviembre de 2003',
      'fileName' => 'BITACORA.-La-Internacionalizacion-de-la-educacion-superior.pdf',
    ],
    [
      'title' => 'Aportes para una discusión sobre áreas universitarias',
      'description' => '',
      'date' => 'Setiembre de 1998',
      'fileName' => 'Aportes-para-una-discusion-sobre-areas-universitarias.pdf',
    ],
    [
      'title' => 'Algunas consideraciones sobre los alcances de la Enseñanza Terciaria',
      'description' => '',
      'date' => 'Abril de 2001',
      'fileName' => 'Algunas-consideraciones-sobre-los-alcances-de-la-Ensenanza-Terciaria.pdf',
    ],
    [
      'title' => '¿Qué es una Universidad?',
      'description' => 'Conferencia dictada en la Facultad de Odontología',
      'date' => 'Agosto de 1994',
      'fileName' => 'Que-es-una-Universidad.pdf',
    ],
    [
      'title' => '¿Existe la libertad académica?',
      'description' => 'Reunión conjunta de la Asociación Internacional de Universidades (AIU) y la Unión de Universidades de América Latina (UDUAL), realizada en México en noviembre de 2001.',
      'date' => 'Octubre de 2001',
      'fileName' => 'Existe-la-libertad-academica.pdf',
    ],
    [
      'title' => 'Discurso acto ASCEEP-FEUU junio 1988',
      'description' => 'Versión abreviada de las palabras pronuncaidas por el delegado docente en el CDC, Dr. Jorge Ares Pons',
      'date' => '22 de junio de 1988',
      'fileName' => 'Discurso acto ASCEEP-FEUU junio 1988.pdf',
      'new' => true,
    ],
    [
      'title' => 'El cangrejo de las elecciones universitarias',
      'description' => '',
      'date' => '',
      'fileName' => 'El cangrejo de las elecciones universitarias.jpg',
      'new' => true,
    ],
    [
      'title' => 'Informe sobre padrones electorales del orden estudiantil y calidad de estudiante (a los fines electorales)',
      'description' => '',
      'date' => 'Marzo de 1993',
      'fileName' => 'Informe sobre padrones electorales del orden estudiantil y calidad de estudiante (a los fines electorales).pdf',
      'new' => true,
    ],
    [
      'title' => 'La Universidad política',
      'description' => 'Publicado en la Gaceta Universitaria',
      'date' => 'Agosto de 1988',
      'fileName' => 'La Universidad política.pdf',
      'new' => true,
    ],
    [
      'title' => 'La Universidad política - Addenda',
      'description' => '',
      'date' => '',
      'fileName' => 'La Universidad política - Addenda.pdf',
      'new' => true,
    ],
    [
      'title' => 'La Universidad y su inserción en la nueva democracia',
      'description' => '',
      'date' => 'Diciembre de 1986',
      'fileName' => 'La Universidad y su inserción en la nueva democracia.pdf',
      'new' => true,
    ],
    [
      'title' => 'Proyecto de adicción al estatuto de personal docente',
      'description' => '',
      'date' => 'Enero de 1986',
      'fileName' => 'Proyecto de adicción al estatuto de personal docente.pdf',
      'new' => true,
    ],
    [
      'title' => 'Raíces y sentido del cogobierno universitario',
      'description' => 'Artículo publicado (en versión incompleta) en la revista "CATÁLISIS" (editada por los estudiantes de la Facultad de Química)',
      'date' => 'Agosto de 1982',
      'fileName' => 'Raíces y sentido del cogobierno universitario.pdf',
      'new' => true,
    ],
    [
      'title' => 'Universidad, educación superior y nivel terciario',
      'description' => 'Publicado en la Gaceta Universitaria',
      'date' => '1988',
      'fileName' => 'Universidad, educación superior y nivel terciario.pdf',
      'new' => true,
    ],
    [
      'title' => 'Universidad Testimonio vivo de democracia',
      'description' => '',
      'date' => '',
      'fileName' => 'Universidad Testimonio vivo de democracia.pdf',
      'new' => true,
    ],
  ],
  'Universidades-privadas' => [
    [
      'title' => 'Niveles de titulación',
      'description' => 'EXPEDICION DE TITULOS DE CARRERAS DE INSTITUCIONES UNIVERSITARIAS PRIVADAS',
      'date' => 'Octubre de 2008',
      'fileName' =>  'Titulos-Privadas.pdf',
    ],
    [
      'title' => 'Situación patrimonial y contable de instituciones universitarias privadas sin fines de lucro',
      'description' => '',
      'date' => 'Noviembre de 2008',
      'fileName' =>  'Situacion-patrimonial-y-contable-de-instituciones-universitarias-privadas-sin-fines-de-lucro.pdf',
    ],
    [
      'title' => 'Proyecto Storace-Palomeque',
      'description' => 'Comisión Central de Educación',
      'date' => 'Marzo de 1992',
      'fileName' =>  'Proyecto-Storace-Palomeque.pdf',
    ],
    [
      'title' => 'Proyecto Fau',
      'description' => '',
      'date' => 'Julio de 2003',
      'fileName' =>  'Proyecto-Fau.pdf',
    ],
    [
      'title' => 'Correspondencia al ministro Guzmán',
      'description' => 'Consejo Consultivo de Enseñanza Terciaria Privada',
      'date' => 'Setiembre de 2004',
      'fileName' =>  'Posgrados-Guzman.pdf',
    ],
    [
      'title' => 'EL GOBIERNO DE LAS INSTITUCIONES UNIVERSITARIAS PRIVADAS SEGÚN EL DEC. 308/995. PERSONERIA JURIDICA Y PERSONERIA ACADEMICA',
      'description' => '',
      'date' => 'Noviembre de 2007',
      'fileName' =>  'Personeria-juridica-y-academica.pdf',
    ],
    [
      'title' => 'Normativa aplicable a las instituciones privadas',
      'description' => 'Decretos 308/995 y 309/002',
      'date' => 'Noviembre de 2011',
      'fileName' =>  'Normativa-aplicable-a-las-instituciones-privadas.pdf',
    ],
    [
      'title' => 'EL MEC Y LA EDUCACION SUPERIOR PRIVADA',
      'description' => '',
      'fileName' =>  'MEC-y-privados.pdf',
    ],
    [
      'title' => 'Dirección de Educación del MEC y Consejo Consultivo de Enseñanza Terciaria Privada (CCETP)',
      'description' => '',
      'fileName' =>  'MEC-y-CCETP.pdf',
    ],
    [
      'title' => 'Transformación de un Instituto Universitario en Universidad de acuerdo a la normativa vigente',
      'description' => '',
      'date' => 'Julio de 2008',
      'fileName' =>  'Instituto-vs-Universidad.-Dictamen.-Julio-2008.pdf',
    ],
    [
      'title' => 'Algunos comentarios informales sobre la posibilidad de transformación de un Instituto Universitario en Universidad',
      'description' => '',
      'date' => 'febrero de 2008',
      'fileName' =>  'Instituto-vs.-Universidad.-Febrero-2008.pdf',
    ],
    [
      'title' => 'ESTATUTOS DE ASOCIACIONES CIVILES PARA INSTITUCIONES UNIVERSITARIAS Problema: Injerencia de los órganos administrativos en aspectos académicos',
      'description' => '',
      'date' => 'Julio de 2005',
      'fileName' =>  'Injerencia-administrativa-en-universidades-privadas.pdf',
    ],
    [
      'title' => 'Instituciones universitarias públicas y privadas. Compatibilidad del ejercicio simultáneo de la docencia, de funciones de dirección u otras similares',
      'description' => '',
      'date' => 'Agosto de 2006',
      'fileName' =>  'Incompatibilidades-publico-y-privado.pdf',
    ],
    [
      'title' => 'Fanelli y Balán: Expansión de la oferta universitaria. Nuevas instituciones, nuevos programas',
      'description' => 'Centro de Estudios de Estado y Sociedad (CEDES)',
      'date' => '1994',
      'fileName' =>  'Fanelli-Balan.-Universidades-Privadas.pdf',
    ],
    [
      'title' => 'Concepto de Facultad',
      'description' => '',
      'date' => 'Julio de 1992',
      'fileName' =>  'Facultad-(significado).pdf',
    ],
    [
      'title' => 'La enseñanza terciaria privada en el Uruguay. Legislación vigente.',
      'description' => '16 años de Consejo Consultivo de Enseñanza Terciaria Privada (CCETP)',
      'date' => 'Abril de 2012',
      'fileName' =>  'Ensenanza-terciaria-privada-en-el-Uruguay.-Legislacion-vigente.pdf',
    ],
    [
      'title' => 'Personal docente de instituciones universitarias privadas',
      'description' => '',
      'date' => 'Setiembre de 2007',
      'fileName' =>  'Docentes-de-instituciones-privadas.pdf',
    ],
    [
      'title' => 'Dictamen 328: Maestrías académicas y Maestrías profesionales',
      'description' => '',
      'fileName' =>  'Dictamen-No-328-(maestrias-academicas-y-profesionales).pdf',
    ],
    [
      'title' => 'Dictamen 244: Valoración académica del personal docente universitario',
      'description' => '',
      'date' => 'Julio de 2007',
      'fileName' =>  'Dictamen-No-244-(doctorados).pdf',
    ],
    [
      'title' => 'Dictamen 232: Suficiencia académica del personal docente',
      'description' => '',
      'date' => 'Noviembre de 2006',
      'fileName' =>  'Dictamen-No-232-(personal-docente).pdf',
    ],
    [
      'title' => 'Dictamen 222: Personal docente a cargo de los Doctorados',
      'description' => '',
      'date' => 'Agosto de 2006',
      'fileName' =>  'Dictamen-No-222-(alcances-Dec.308995).pdf',
    ],
    [
      'title' => 'Dictamen 293: Instituto Universitario Maldonado - Punta del Este',
      'description' => '',
      'date' => 'Diciembre de 2009',
      'fileName' =>  'dictamen-293-Maldonado-Punta-del-Este.pdf',
    ],
    [
      'title' => 'Comisión Previo CCETP',
      'description' => '',
      'fileName' =>  'Comision-Previo-CCETP.pdf',
    ],
    [
      'title' => 'Comentarios sobre dictado de carreras no presentadas',
      'description' => '',
      'date' => 'Diciembre de 2010',
      'fileName' =>  'Comentarios-sobre-dictado-de-carreras-no-presentadas.pdf',
    ],
    [
      'title' => 'Especialización en Ciencia y Tecnología de Alimentos (Acotaciones sobre conceptos y contenidos)',
      'description' => '',
      'date' => 'Marzo de 2008',
      'fileName' =>  'Ciencia-y-Tecnologia-de-Alimentos.-Especializacion.pdf',
    ],
    [
      'title' => 'CCETP y CUETP para Rector',
      'description' => '',
      'date' => 'Junio de 2006',
      'fileName' =>  'CCETP-y-CUETP-para-Rector.pdf',
    ],
    [
      'title' => 'El concepto de autonomía en el decreto 308/995',
      'description' => '',
      'date' => 'Abril de 2010',
      'fileName' =>  'Autonomia-academica-y-dec.308-995.pdf',
    ],
    [
      'title' => 'Fundamento de voto sobre la "Licenciatura en Arquitectura de Interiores" presentada por la institución ORT',
      'description' => '',
      'date' => 'Diciembre de 2004',
      'fileName' =>  'Arquitecto-ORT.pdf',
    ],
  ],
];
